// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFAm9GxzXStjPDcayN_HbpiaMC3zFROa0',
    appId: '1:181263897303:web:cc116341b1b28dfd4a1692',
    messagingSenderId: '181263897303',
    projectId: 'crud-firebase-youtube',
    authDomain: 'crud-firebase-4cbdf.firebaseapp.com',
    storageBucket: 'crud-firebase-youtube.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMEson-13YDm1bk9DH9m57lLLAtsK9RyY',
    appId: '1:181263897303:android:770700be1802da194a1692',
    messagingSenderId: '181263897303',
    projectId: 'crud-firebase-youtube',
    storageBucket: 'crud-firebase-youtube.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2nDkZ5ZxhOJJogIv2TrTKD69asF7zoos',
    appId: '1:181263897303:ios:3918e38b7ed224584a1692',
    messagingSenderId: '181263897303',
    projectId: 'crud-firebase-youtube',
    storageBucket: 'crud-firebase-youtube.appspot.com',
    iosClientId: '181263897303-m2a9j4gnaksisgg4dk8vh5g6ujp2vdv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2nDkZ5ZxhOJJogIv2TrTKD69asF7zoos',
    appId: '1:181263897303:ios:860a70220be3e9214a1692',
    messagingSenderId: '181263897303',
    projectId: 'crud-firebase-youtube',
    storageBucket: 'crud-firebase-youtube.appspot.com',
    iosClientId: '181263897303-r59u95b96omu0spqaqv9e68r27rojtcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
